FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime

RUN pip install --no-cache-dir \
    transformers==4.40.0 \
    datasets==2.19.0 \
    mlflow==2.13.0 \
    onnx==1.16.0 \
    onnxruntime==1.18.0

COPY ml/train.py /app/train.py
WORKDIR /app

ENTRYPOINT ["python", "train.py"]
